package app.mutah.enums;

import com.fasterxml.jackson.annotation.JsonProperty;

public enum Country {
    @JsonProperty("af")
    AF,
    @JsonProperty("al")
    AL,
    @JsonProperty("dz")
    DZ,
    @JsonProperty("ad")
    AD,
    @JsonProperty("ao")
    AO,
    @JsonProperty("ag")
    AG,
    @JsonProperty("ar")
    AR,
    @JsonProperty("am")
    AM,
    @JsonProperty("aw")
    AW,
    @JsonProperty("au")
    AU,
    @JsonProperty("at")
    AT,
    @JsonProperty("az")
    AZ,
    @JsonProperty("bs")
    BS,
    @JsonProperty("bh")
    BH,
    @JsonProperty("bd")
    BD,
    @JsonProperty("bb")
    BB,
    @JsonProperty("by")
    BY,
    @JsonProperty("be")
    BE,
    @JsonProperty("bz")
    BZ,
    @JsonProperty("bj")
    BJ,
    @JsonProperty("bt")
    BT,
    @JsonProperty("bo")
    BO,
    @JsonProperty("ba")
    BA,
    @JsonProperty("bw")
    BW,
    @JsonProperty("br")
    BR,
    @JsonProperty("bg")
    BG,
    @JsonProperty("bf")
    BF,
    @JsonProperty("bi")
    BI,
    @JsonProperty("kh")
    KH,
    @JsonProperty("cm")
    CM,
    @JsonProperty("ca")
    CA,
    @JsonProperty("cf")
    CF,
    @JsonProperty("td")
    TD,
    @JsonProperty("cl")
    CL,
    @JsonProperty("cn")
    CN,
    @JsonProperty("co")
    CO,
    @JsonProperty("km")
    KM,
    @JsonProperty("cr")
    CR,
    @JsonProperty("hr")
    HR,
    @JsonProperty("cu")
    CU,
    @JsonProperty("cy")
    CY,
    @JsonProperty("dk")
    DK,
    @JsonProperty("dj")
    DJ,
    @JsonProperty("dm")
    DM,
    @JsonProperty("do")
    DO,
    @JsonProperty("ec")
    EC,
    @JsonProperty("eg")
    EG,
    @JsonProperty("sv")
    SV,
    @JsonProperty("gq")
    GQ,
    @JsonProperty("er")
    ER,
    @JsonProperty("ee")
    EE,
    @JsonProperty("et")
    ET,
    @JsonProperty("fj")
    FJ,
    @JsonProperty("fi")
    FI,
    @JsonProperty("fr")
    FR,
    @JsonProperty("ga")
    GA,
    @JsonProperty("gm")
    GM,
    @JsonProperty("ge")
    GE,
    @JsonProperty("de")
    DE,
    @JsonProperty("gh")
    GH,
    @JsonProperty("gr")
    GR,
    @JsonProperty("gd")
    GD,
    @JsonProperty("gt")
    GT,
    @JsonProperty("gn")
    GN,
    @JsonProperty("gw")
    GW,
    @JsonProperty("gy")
    GY,
    @JsonProperty("ht")
    HT,
    @JsonProperty("hn")
    HN,
    @JsonProperty("hk")
    HK,
    @JsonProperty("hu")
    HU,
    @JsonProperty("is")
    IS,
    @JsonProperty("in")
    IN,
    @JsonProperty("id")
    ID,
    @JsonProperty("iq")
    IQ,
    @JsonProperty("ie")
    IE,
    @JsonProperty("il")
    IL,
    @JsonProperty("it")
    IT,
    @JsonProperty("jm")
    JM,
    @JsonProperty("jp")
    JP,
    @JsonProperty("jo")
    JO,
    @JsonProperty("kz")
    KZ,
    @JsonProperty("ke")
    KE,
    @JsonProperty("ki")
    KI,
    @JsonProperty("xk")
    XK,
    @JsonProperty("kw")
    KW,
    @JsonProperty("kg")
    KG,
    @JsonProperty("lv")
    LV,
    @JsonProperty("lb")
    LB,
    @JsonProperty("ls")
    LS,
    @JsonProperty("lr")
    LR,
    @JsonProperty("li")
    LI,
    @JsonProperty("lt")
    LT,
    @JsonProperty("lu")
    LU,
    @JsonProperty("mg")
    MG,
    @JsonProperty("mw")
    MW,
    @JsonProperty("my")
    MY,
    @JsonProperty("mv")
    MV,
    @JsonProperty("ml")
    ML,
    @JsonProperty("mt")
    MT,
    @JsonProperty("mh")
    MH,
    @JsonProperty("mr")
    MR,
    @JsonProperty("mu")
    MU,
    @JsonProperty("mx")
    MX,
    @JsonProperty("mc")
    MC,
    @JsonProperty("mn")
    MN,
    @JsonProperty("me")
    ME,
    @JsonProperty("ma")
    MA,
    @JsonProperty("mz")
    MZ,
    @JsonProperty("mm")
    MM,
    @JsonProperty("na")
    NA,
    @JsonProperty("nr")
    NR,
    @JsonProperty("np")
    NP,
    @JsonProperty("nl")
    NL,
    @JsonProperty("nz")
    NZ,
    @JsonProperty("ni")
    NI,
    @JsonProperty("ne")
    NE,
    @JsonProperty("ng")
    NG,
    @JsonProperty("no")
    NO,
    @JsonProperty("om")
    OM,
    @JsonProperty("pk")
    PK,
    @JsonProperty("pw")
    PW,
    @JsonProperty("pa")
    PA,
    @JsonProperty("pg")
    PG,
    @JsonProperty("py")
    PY,
    @JsonProperty("pe")
    PE,
    @JsonProperty("ph")
    PH,
    @JsonProperty("pl")
    PL,
    @JsonProperty("pt")
    PT,
    @JsonProperty("qa")
    QA,
    @JsonProperty("md")
    MD,
    @JsonProperty("sy")
    SY,
    @JsonProperty("tw")
    TW,
    @JsonProperty("ru")
    RU,
    @JsonProperty("ro")
    RO,
    @JsonProperty("vn")
    VN,
    @JsonProperty("rw")
    RW,
    @JsonProperty("kn")
    KN,
    @JsonProperty("lc")
    LC,
    @JsonProperty("ly")
    LY,
    @JsonProperty("ps")
    PS,
    @JsonProperty("ir")
    IR,
    @JsonProperty("kr")
    KR,
    @JsonProperty("kp")
    KP,
    @JsonProperty("vc")
    VC,
    @JsonProperty("ws")
    WS,
    @JsonProperty("sm")
    SM,
    @JsonProperty("st")
    ST,
    @JsonProperty("sa")
    SA,
    @JsonProperty("sn")
    SN,
    @JsonProperty("rs")
    RS,
    @JsonProperty("sc")
    SC,
    @JsonProperty("sl")
    SL,
    @JsonProperty("sg")
    SG,
    @JsonProperty("sx")
    SX,
    @JsonProperty("sk")
    SK,
    @JsonProperty("si")
    SI,
    @JsonProperty("sb")
    SB,
    @JsonProperty("so")
    SO,
    @JsonProperty("za")
    ZA,
    @JsonProperty("ss")
    SS,
    @JsonProperty("es")
    ES,
    @JsonProperty("lk")
    LK,
    @JsonProperty("sd")
    SD,
    @JsonProperty("sr")
    SR,
    @JsonProperty("sz")
    SZ,
    @JsonProperty("se")
    SE,
    @JsonProperty("ch")
    CH,
    @JsonProperty("tj")
    TJ,
    @JsonProperty("th")
    TH,
    @JsonProperty("tl")
    TL,
    @JsonProperty("tg")
    TG,
    @JsonProperty("to")
    TO,
    @JsonProperty("tt")
    TT,
    @JsonProperty("tn")
    TN,
    @JsonProperty("tr")
    TR,
    @JsonProperty("tm")
    TM,
    @JsonProperty("tv")
    TV,
    @JsonProperty("ug")
    UG,
    @JsonProperty("ua")
    UA,
    @JsonProperty("ae")
    AE,
    @JsonProperty("gb")
    GB,
    @JsonProperty("us")
    US,
    @JsonProperty("uy")
    UY,
    @JsonProperty("uz")
    UZ,
    @JsonProperty("vu")
    VU,
    @JsonProperty("ve")
    VE,
    @JsonProperty("ye")
    YE,
    @JsonProperty("zm")
    ZM,
    @JsonProperty("zw")
    ZW;
}